resources:
- name: check-a-record
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/check-a-record.git

jobs:
- name: test-check-a-record
  public: true
  plan:
  - get: check-a-record
    trigger: true
  - task: test
    file: check-a-record/ci/test.yml

